version: '3'

services:
  postgress:
    image: postgres:latest
    container_name: DB_ANALYTICS_DATA
    restart: always
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: analytics_data
    volumes:
      - ./database/postgres:/data/postgres
    ports:
      - "4553:5432"